server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
